"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const trupmena_1 = require("./trupmena");
const t1 = new trupmena_1.Trupmena(1, 1, 2);
const t2 = new trupmena_1.Trupmena(2, 3, 4);
t1.pridetiTrupmena(t2);
t2.pridetiInt(2);
t2.pridetiTrupmena(t1);
console.log(t1.toString());
//t1.skaitiklis=3;
//t1.prideti(0,1,3);
//console.log(t1.toString());
